"""ADR-0043 P1 — the parser's ``details`` payload reaches the sidecar tables.

Two tiers.

**Hermetic** — the coercion layer, and the cross-language wire contract. The
payload arrives as JSON over HTTP from a Rust service, which is the classic
place for a silent failure: rename a field on one side, and every column
quietly writes NULL while the import logs success. So the fixture at
``tests/fixtures/parser_details_payload.json`` is **generated by the Rust
test suite** (``cargo test emit_wire_fixture``) and asserted against by both
sides — Rust checks the checked-in copy still matches what it emits, and the
tests here check every key in it lands somewhere real.

**Real-Postgres** (opt-in on ``DOC_TEST_PG_URL``) — drives the actual import
path end to end and counts rows, because "the writer function returned True"
is not evidence that anything was stored.
"""

from __future__ import annotations

import json
import os
import uuid
from datetime import datetime
from pathlib import Path

import pytest

os.environ.setdefault("DATABASE_URL", "postgresql+asyncpg://test:test@localhost/test")
os.environ.setdefault("JWT_SECRET_KEY", "test_secret_key_unused_in_unit_tests")
os.environ.setdefault("REDIS_URL", "redis://localhost:6379/15")

from sqlalchemy import SmallInteger, String

from app.models.flight_details import FlightDetails, FlightSeries
from app.services.flight_details_writer import (
    MAX_SAMPLES_PER_SERIES,
    MAX_SERIES_PER_FLIGHT,
    _coerce,
    build_details_values,
    build_series_rows,
)

FIXTURE = Path(__file__).parent / "fixtures" / "parser_details_payload.json"

#: Keys the parser emits that are NOT ``flight_details`` columns. Each is
#: consumed elsewhere or deliberately dropped — enumerated so a genuinely new,
#: unmapped key shows up as a failure instead of vanishing.
NON_COLUMN_KEYS = {
    "series",  # → flight_series rows
}


@pytest.fixture(scope="module")
def payload() -> dict:
    assert FIXTURE.exists(), (
        f"{FIXTURE} is missing — regenerate it from the parser with:\n"
        "  cd flight-parser && DETAILS_FIXTURE_OUT=../backend/tests/fixtures/"
        "parser_details_payload.json cargo test emit_wire_fixture"
    )
    return json.loads(FIXTURE.read_text())


# ── The cross-language wire contract ───────────────────────────────────


def test_every_payload_key_is_a_real_column_or_explicitly_excluded(payload):
    """A field renamed on the Rust side must fail here, loudly.

    Without this the failure mode is: the parser emits ``photoCount``, the
    writer looks for ``photo_count``, finds nothing, writes NULL — and every
    import still logs "Flight details stored". Silent, permanent, and it looks
    exactly like success.
    """
    columns = {c.name for c in FlightDetails.__table__.columns}
    unmapped = set(payload) - columns - NON_COLUMN_KEYS
    assert not unmapped, (
        f"parser emits keys with no flight_details column: {sorted(unmapped)}. "
        "Either add the column, or add the key to NON_COLUMN_KEYS with a "
        "reason."
    )


def test_the_fixture_is_populated_not_a_shell(payload):
    """A fixture of nulls would make every assertion below vacuously true."""
    scalars = {k: v for k, v in payload.items() if k not in NON_COLUMN_KEYS}
    non_null = {k: v for k, v in scalars.items() if v not in (None, [], {})}
    assert len(non_null) >= 40, f"only {len(non_null)} populated fields"
    assert payload["frame_count"] == 20
    assert payload["photo_count"] == 2
    assert len(payload["series"]) == 15


def test_the_payload_covers_every_column_type_the_writer_coerces(payload):
    """The fixture must exercise each coercion branch, or the coercion layer
    is only tested by its unit tests and never by a real payload."""
    values = build_details_values(payload)
    assert isinstance(values["frame_count"], int)
    assert isinstance(values["max_altitude_msl_m"], float)
    assert isinstance(values["is_beginner_mode"], bool)
    assert isinstance(values["parser_version"], str)
    assert isinstance(values["first_frame_at"], datetime)
    assert isinstance(values["phases"], list)
    assert isinstance(values["config"], dict)


def test_rfc3339_timestamps_become_naive_utc(payload):
    """The parser emits ``...+00:00``; every DateTime column in this repo is
    naive UTC. Storing an aware value is the ADR-0017 class of bug."""
    values = build_details_values(payload)
    for column in ("first_frame_at", "last_frame_at"):
        dt = values[column]
        assert isinstance(dt, datetime)
        assert dt.tzinfo is None, f"{column} must be naive UTC"
    assert values["first_frame_at"] == datetime(2025, 9, 5, 0, 0, 0)
    assert values["last_frame_at"] == datetime(2025, 9, 5, 0, 0, 19)


def test_series_rows_are_built_one_per_named_series(payload):
    fid = uuid.uuid4()
    rows = build_series_rows(fid, payload)
    assert len(rows) == 15
    by_name = {r["name"]: r for r in rows}
    assert "t_offset_s" in by_name
    assert by_name["altitude_msl_m"]["unit"] == "m"
    assert by_name["altitude_msl_m"]["precision_dp"] == 1
    assert by_name["battery_current_a"]["unit"] == "A"
    assert by_name["t_offset_s"]["unit"] == "s"
    for row in rows:
        assert row["flight_id"] == fid
        assert row["source"] == "frame"
        assert row["sample_count"] == 20
        assert len(row["values"]) == 20


def test_series_are_index_aligned_to_the_time_base(payload):
    """The read path's alignment guarantee is only true if the write side
    stores equal-length series. Assert it on the real payload."""
    rows = build_series_rows(uuid.uuid4(), payload)
    lengths = {len(r["values"]) for r in rows if r["source"] == "frame"}
    assert lengths == {20}, f"frame series have mismatched lengths: {lengths}"


def test_missing_samples_survive_as_nulls(payload):
    """The parser emits null for a sample the aircraft never reported. If the
    writer coerced those to 0.0 the chart would show 'signal lost' where the
    truth is 'no report' — a different and alarming claim."""
    rows = {r["name"]: r for r in build_series_rows(uuid.uuid4(), payload)}
    downlink = rows["rc_downlink"]["values"]
    assert downlink[0] is None
    assert downlink[1] is None
    assert 0.0 in downlink, "the fixture should also contain a real zero-signal frame"
    assert downlink.count(None) == 2


def test_recorded_limits_arrive_without_commentary(payload):
    """ADR-0029 / ADR-0031: a height limit is data. Nothing in the payload
    may editorialize about it."""
    values = build_details_values(payload)
    assert values["height_limit_m"] == 120.0
    assert values["max_allowed_height_m"] == 500.0
    blob = json.dumps(payload).lower()
    for banned in ("part 107", "part-107", "exceed", "violation", "400 ft"):
        assert banned not in blob


def test_take_off_altitude_arrives_raw_and_flagged(payload):
    """§9 C-1 — carried but never displayed until a second airframe confirms
    the scale."""
    values = build_details_values(payload)
    assert values["take_off_altitude_raw"] == 1938.0
    assert values["take_off_altitude_units"] == "unconfirmed"


# ── Coercion: the payload is remote input ──────────────────────────────


def test_unknown_keys_are_ignored_not_fatal():
    """A newer parser talking to an older backend must degrade, not crash."""
    values = build_details_values({"frame_count": 5, "a_field_from_the_future": 1})
    assert values["frame_count"] == 5
    assert "a_field_from_the_future" not in values


def test_wrong_typed_values_become_null_rather_than_raising():
    values = build_details_values({
        "frame_count": "not a number",
        "max_altitude_msl_m": {"nope": 1},
        "is_beginner_mode": None,
        "first_frame_at": "definitely not a date",
        "phases": "should be a list",
    })
    assert values["frame_count"] is None
    assert values["max_altitude_msl_m"] is None
    assert values["first_frame_at"] is None
    assert values["phases"] is None


def test_out_of_range_integers_become_null_not_a_dataerror():
    """Postgres ``integer`` is 4 bytes and ``smallint`` 2. An i64 from the
    parser that overflows either would raise mid-import; NULL is the honest
    degradation."""
    assert _coerce(2**31, FlightDetails.__table__.c.frame_count.type, "x") is None
    assert _coerce(2**31 - 1, FlightDetails.__table__.c.frame_count.type, "x") == 2**31 - 1
    assert _coerce(40_000, SmallInteger(), "x") is None
    assert _coerce(32_767, SmallInteger(), "x") == 32_767
    assert _coerce(-32_769, SmallInteger(), "x") is None


def test_non_finite_floats_become_null():
    """NaN and inf have no SQL representation and no meaning as a reading."""
    col = FlightDetails.__table__.c.max_altitude_msl_m.type
    assert _coerce(float("nan"), col, "x") is None
    assert _coerce(float("inf"), col, "x") is None
    assert _coerce(-float("inf"), col, "x") is None
    assert _coerce(193.9, col, "x") == 193.9


def test_overlong_strings_are_truncated_to_the_column_width():
    assert _coerce("x" * 100, String(16), "x") == "x" * 16


def test_series_sample_count_is_recomputed_not_trusted():
    """A payload claiming a count that disagrees with its array would make the
    read path's ``sample_count`` a lie."""
    rows = build_series_rows(uuid.uuid4(), {
        "series": [{"source": "frame", "name": "a", "sample_count": 9999, "values": [1, 2, 3]}]
    })
    assert rows[0]["sample_count"] == 3


def test_malformed_series_blocks_are_skipped_individually():
    rows = build_series_rows(uuid.uuid4(), {
        "series": [
            {"source": "frame", "name": "good", "values": [1.0]},
            {"source": 42, "name": "bad_source", "values": [1.0]},
            {"source": "frame", "name": None, "values": [1.0]},
            {"source": "frame", "name": "no_values"},
            {"source": "frame", "name": "values_not_a_list", "values": "nope"},
            "not even a dict",
        ]
    })
    assert [r["name"] for r in rows] == ["good"]


def test_duplicate_series_keys_do_not_violate_the_primary_key():
    """(flight_id, source, name) is the PK. Two blocks with the same key would
    raise on insert and lose the whole details write."""
    rows = build_series_rows(uuid.uuid4(), {
        "series": [
            {"source": "frame", "name": "dup", "values": [1.0]},
            {"source": "frame", "name": "dup", "values": [2.0, 3.0]},
        ]
    })
    assert len(rows) == 1
    assert rows[0]["values"] == [1.0]


def test_an_absurdly_large_series_is_refused():
    """Bounds the memory a remote service can make this process allocate."""
    rows = build_series_rows(uuid.uuid4(), {
        "series": [
            {"source": "frame", "name": "huge", "values": [0.0] * (MAX_SAMPLES_PER_SERIES + 1)},
            {"source": "frame", "name": "fine", "values": [0.0] * 10},
        ]
    })
    assert [r["name"] for r in rows] == ["fine"]


def test_too_many_series_are_capped():
    rows = build_series_rows(uuid.uuid4(), {
        "series": [
            {"source": "frame", "name": f"s{i}", "values": [0.0]}
            for i in range(MAX_SERIES_PER_FLIGHT + 20)
        ]
    })
    assert len(rows) == MAX_SERIES_PER_FLIGHT


def test_a_payload_that_is_not_a_dict_yields_nothing():
    assert build_series_rows(uuid.uuid4(), {"series": "nope"}) == []
    assert build_series_rows(uuid.uuid4(), {}) == []


# ── Real Postgres: the import path, counted ────────────────────────────

_PG_URL = os.environ.get("DOC_TEST_PG_URL")
pg_integration = pytest.mark.skipif(
    not _PG_URL,
    reason="set DOC_TEST_PG_URL (postgresql+asyncpg://…) to run real-DB persistence tests",
)


def _base_parsed(**overrides) -> dict:
    parsed = {
        "start_time": "2025-09-05T00:00:00+00:00",
        "duration_secs": 19.0,
        "total_distance": 211.3,
        "max_altitude": 76.5,
        "max_speed": 8.2,
        "home_lat": 44.0521,
        "home_lon": -123.0868,
        "point_count": 20,
        "gps_track": [{"lat": 44.0521, "lng": -123.0868, "alt": 1.0}],
        "telemetry": {"altitude": [1.0], "speed": [0.1]},
        "raw_metadata": {"product_type": "Unknown(178)", "aircraft_name": "Matrice 4TD"},
        "source": "dji_txt",
        "drone_model": "Matrice 4TD",
        "drone_serial": "1581F8HGX255P00A",
        "original_filename": "DJIFlightRecord_test.txt",
    }
    parsed.update(overrides)
    return parsed


@pytest.fixture
async def db_session():
    """A session against a freshly built schema on the throwaway Postgres."""
    from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

    from app.database import Base
    import app.models  # noqa: F401

    engine = create_async_engine(_PG_URL, poolclass=None)
    async with engine.begin() as conn:
        await conn.run_sync(lambda c: Base.metadata.drop_all(bind=c))
        await conn.run_sync(lambda c: Base.metadata.create_all(bind=c))
    maker = async_sessionmaker(engine, expire_on_commit=False)
    async with maker() as session:
        yield session
    await engine.dispose()


async def _count(session, model) -> int:
    from sqlalchemy import func, select

    return (await session.execute(select(func.count()).select_from(model))).scalar()


@pg_integration
@pytest.mark.asyncio
async def test_a_payload_with_details_writes_one_row_and_n_series(db_session, payload):
    from app.routers.flight_library import _build_flight_from_parsed

    flight = await _build_flight_from_parsed(
        db_session, _base_parsed(details=payload), "hash-with-details", "f.txt"
    )
    await db_session.commit()

    assert flight is not None
    assert await _count(db_session, FlightDetails) == 1
    assert await _count(db_session, FlightSeries) == 15

    row = await db_session.get(FlightDetails, flight.id)
    assert row.frame_count == 20
    assert row.photo_count == 2
    assert row.max_altitude_msl_m == 209.0
    assert row.parser_version == payload["parser_version"]
    assert row.crate_version == "0.5.7"
    assert row.first_frame_at == datetime(2025, 9, 5, 0, 0, 0)
    assert row.take_off_altitude_units == "unconfirmed"
    assert row.schema_version == 1
    assert row.generated_at is not None
    # JSONB groups survive the round trip.
    assert [p["state"] for p in row.phases] == ["Hover", "GPSSport"]
    assert row.health["is_vibrating"] == 1
    assert row.config["time_base"] == "date_time"


@pg_integration
@pytest.mark.asyncio
async def test_a_payload_without_details_writes_nothing(db_session):
    from app.routers.flight_library import _build_flight_from_parsed

    flight = await _build_flight_from_parsed(
        db_session, _base_parsed(), "hash-no-details", "f.txt"
    )
    await db_session.commit()

    assert flight is not None, "the flight itself must still import"
    assert await _count(db_session, FlightDetails) == 0
    assert await _count(db_session, FlightSeries) == 0


@pg_integration
@pytest.mark.asyncio
@pytest.mark.parametrize(
    "bad_details",
    [
        pytest.param("not a dict", id="string"),
        pytest.param([1, 2, 3], id="list"),
        pytest.param({"frame_count": "garbage", "series": "not a list"}, id="wrong-types"),
        pytest.param({"series": [{"source": "frame", "name": "x", "values": "nope"}]}, id="bad-series"),
        pytest.param({"frame_count": 2**40}, id="int-overflow"),
        pytest.param({"first_frame_at": "not-a-date"}, id="bad-datetime"),
    ],
)
async def test_malformed_details_is_swallowed_and_the_flight_still_imports(
    db_session, bad_details
):
    """The contract that matters most. Extended data is a nice-to-have; the
    flight record is the operator's actual work product. A details failure
    costs a WARN line and nothing else."""
    from app.routers.flight_library import _build_flight_from_parsed

    flight = await _build_flight_from_parsed(
        db_session, _base_parsed(details=bad_details), "hash-bad", "f.txt"
    )
    await db_session.commit()

    assert flight is not None, "a bad details payload must never fail the import"
    assert flight.duration_secs == 19.0
    assert flight.point_count == 20
    # The session is still usable — no poisoned transaction left behind.
    assert await _count(db_session, FlightSeries) in (0, 1)


@pg_integration
@pytest.mark.asyncio
async def test_repersisting_replaces_series_wholesale(db_session, payload):
    """A re-parse producing fewer series must not leave stale rows behind —
    they would be index-misaligned against the new time base and silently
    wrong on a chart."""
    from app.routers.flight_library import _build_flight_from_parsed
    from app.services.flight_details_writer import persist_flight_details

    flight = await _build_flight_from_parsed(
        db_session, _base_parsed(details=payload), "hash-replace", "f.txt"
    )
    await db_session.commit()
    assert await _count(db_session, FlightSeries) == 15

    smaller = dict(payload)
    smaller["series"] = payload["series"][:3]
    smaller["frame_count"] = 7
    await persist_flight_details(db_session, flight.id, smaller)
    await db_session.commit()

    assert await _count(db_session, FlightSeries) == 3
    assert await _count(db_session, FlightDetails) == 1, "upsert, not a second row"
    row = await db_session.get(FlightDetails, flight.id)
    await db_session.refresh(row)
    assert row.frame_count == 7


@pg_integration
@pytest.mark.asyncio
async def test_deleting_the_flight_removes_its_sidecars(db_session, payload):
    from app.routers.flight_library import _build_flight_from_parsed

    flight = await _build_flight_from_parsed(
        db_session, _base_parsed(details=payload), "hash-cascade", "f.txt"
    )
    await db_session.commit()
    assert await _count(db_session, FlightSeries) == 15

    from app.models.flight import Flight

    await db_session.delete(await db_session.get(Flight, flight.id))
    await db_session.commit()

    assert await _count(db_session, FlightDetails) == 0
    assert await _count(db_session, FlightSeries) == 0
